### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by adithirgis** [pratheesh3780/grapesAgri1#1]
Thank you for submitting to JOSS, I enjoyed reviewing this package. Congratulations! 

Starting my review here. To avoid system errors I tried to run this package on [RStudio cloud](https://rstudio.cloud/). 

1. Can you please add references in [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md) using [paper.bib](https://github.com/adithirgis/grapesAgri1/blob/master/paper.bib).
2. Can you please mention whether `grapesAgri1` has been cited or referenced anywhere and if yes where please add it. 
3. As mentioned in the [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md) - 
"Scientist and research students were in trouble to find a suitable platform for their data analysis and also to publish the research output in quality journals. Most of the softwares available for data analysis are proprietary or lacks a simple user interface. Though several online platforms were available for data analysis, they are not much updated up to the current publication standards at international level."
Can the authors please mention software name they have come across which are proprietary, lack simple user interface or not updated to current standards and do not provide graphs, thus providing a comparative study.
4. Also in the [DESCRIPTION](https://github.com/adithirgis/grapesAgri1/blob/master/DESCRIPTION) of the package, please add the version number of the packages which are being imported, this might resolve the conflict of versions. 
5. Styling of the code is not uniform , please refer to this guide for styling or you could also use `styler` package, sometimes `=` is used for assignment and in other places `<-` is used (recommend choosing one style and sticking with it)
eg - 
` result=as.data.frame( anova(anvaTable) );
trtmeans<-out$means `
6. Spacing in code is inconsistent. Also the code lines stretch very long, beyond the recommended 80 characters or 120 characters. Here is a resource which could be helpful - https://devguide.ropensci.org/building.html#code-style, http://adv-r.had.co.nz/Style.html and https://www.tidyverse.org/blog/2017/12/styler-1.0.0/.
7. Can you please point me to the tests folder of this application? I do not seem to find the test folder in the package. Please add test units for automatically testing your application. Tests for functions will also be required. Examples from JOSS - https://github.com/michaellevy/gwdegree/tree/master/tests/testthat, https://github.com/PsyChiLin/EFAshiny/tree/master/tests/testthat, https://github.com/OttaviaE/DscoreApp/tree/master/tests, https://github.com/pmcharrison/psychTestR/tree/master/tests/testthat.
8. I got three notes while checking the package using `devtools::check()`. I would suggest adding `.bib` and `.md` extensions to the `.Rbuildignore` file.  And another problem I faced is that I require `kableExtra` as an import not suggests, because I tried installing the package and it still says I need to install the `kableExtra`, `summarytools`, and for `grapesAgri1::ttApp()` it required `PairedData`. 
` checking package dependencies ... NOTE
Packages suggested but not available for checking:
  'kableExtra', 'summarytools', 'desplot', 'PairedData' `. 
9. When I choose the car.csv and try to use `grapesAgri1::descApp()` without header it shows me this error - 
![image](https://user-images.githubusercontent.com/63432077/124088055-35477580-da70-11eb-99cb-a22d146ddac8.png)

10. For correlation analysis report download in `grapesAgri1::corrApp()` function for Simple_corelation, for html version the formatting looks fine, while the word/docx version does not seem very intuitive, is there a way to format it correctly, and the pdf version is not downloaded in my windows 10 system. Error for pdf version is - `Warning in system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) : '"pdflatex"' not found Warning: Error in : LaTeX failed to compile report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.`-
 
![image](https://user-images.githubusercontent.com/63432077/124088155-4abc9f80-da70-11eb-94e8-292f65436892.png)
![image](https://user-images.githubusercontent.com/63432077/124088184-514b1700-da70-11eb-8cd5-89088086dda6.png)
![image](https://user-images.githubusercontent.com/63432077/124088215-57d98e80-da70-11eb-9cdf-f405124fbdc9.png)

 
11. Also when I don't select any options it shows this error, is it possible to show these errors as warnings or have an option already selected -
 
![image](https://user-images.githubusercontent.com/63432077/124088362-7dff2e80-da70-11eb-95b4-506d596c6f78.png)

12. For this function `grapesAgri1::crdApp()` for the below selected parameters I am not able to generate the table is there some mistake I am making, please explain the data used here `unequal_replication.csv` and others to understand the functionality better -
![image](https://user-images.githubusercontent.com/63432077/124089613-ab98a780-da71-11eb-9e6b-e741f4be643d.png)
 
13.  It would be great if these functions - `grapesAgri1::layoutApp()` and `grapesAgri1::rbdApp()` and its application are explained in the [ReadMe](https://github.com/adithirgis/grapesAgri1#readme) file. And to add both the apps work well with the `mango data.csv`.

14. Paper suggestions - I will [pr](https://github.com/pratheesh3780/grapesAgri1/pull/2), please feel free to ignore some if you feel its not grammatically correct. Changes are in bold and strikeout.

15. Extra suggestion, if possible the Community guidelines can be mentioned in the documentation or the [ReadMe](https://github.com/adithirgis/grapesAgri1#readme) file instead of [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md)

Let me know if you have questions. 
Cheers!
Adithi

**Comment by pratheesh3780** [comment]
Thank you so much for taking your time to give such a detailed review of the package.  All your comments were valuable and will act accordingly.  
1. In comment No.2 . grapesAgri1 package is now available in CRAN, should I mention that because It was released in CRAN after the submission of the paper in JOSS.
2. In comment No. 12 . You may select Treatment as FEED and variable of interest (Response) as WEIGHT. Please see if this was the issue.
3. In comment No.11, I was getting a good formatting in Word . Please help me to identify the issue
<img width="389" alt="example" src="https://user-images.githubusercontent.com/67531873/124128624-971cd500-da9a-11eb-9c46-c3142a4e7e56.PNG">
4. In comment 10. Issue is : To download the results in pdf one may use  `tinytex::install_tinytex()` before using the app. If this may be the issue, I should add it to Readme.
Rest all the comments were clear and will certainly improve the app. I will make the suggested corrections soon.

> Thank you so much

**Comment by adithirgis** [comment]
> In comment No.2 . grapesAgri1 package is now available in CRAN, should I mention that because It was released in CRAN after the submission of the paper in JOSS.

Has the package been referenced anywhere? Meaning its usage has been in a peer reviewed journal article?

> In comment No. 12 . You may select Treatment as FEED and variable of interest (Response) as WEIGHT. Please see if this was the issue.

Yes, Thanks it works now, could you mention the requirements like such in the ReadMe? Will help users to navigate better. 

> In comment No.11, I was getting a good formatting in Word . Please help me to identify the issue

Sorry I get this error in RStudio cloud as well. Could you check using [RStudio cloud](https://rstudio.cloud/)?

> 4. In comment 10. Issue is : To download the results in pdf one may use `tinytex::install_tinytex()` before using the app. If this may be the issue, I should add it to Readme. 

Yes please add all the necessary packages in Imports in [DESCRIPTION](https://github.com/adithirgis/grapesAgri1/blob/master/DESCRIPTION). 


Also if you are making changes to your paper, please update it by calling whedon.
Cheers! 
Adithi

**Comment by pratheesh3780** [comment]
<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/67531873/124142020-7eff8280-daa7-11eb-8e08-d18fa4c33faa.PNG">
It was ok for me from RStudio cloud also. May be issue with ms office. Im using ms office 2019.
Im new to this process, can you please guide me on how to update by calling whedon.
Thank you!

**Comment by adithirgis** [comment]
Oh sure, please go to [this](https://github.com/openjournals/joss-reviews/issues/3437) page and comment `@whedon commands` or `@whedon generate pdf` to generate pdf version of your paper. I am sorry I made a few changes to the paper.md. Please feel free to accept or reject the formatting change. The strikeout is for removing the words or sentences and the bold is for replacing. I hope you understand. 

Yes probably it is the ms office issue, can you please check what would can users do who do not have the latest ms office version? 

Thanks!

**Comment by pratheesh3780** [comment]
1. Can you please add references in paper.md using paper.bib.
 I have already added that, is that ok or any other issue, I didn't understand the comment, sorry
<img width="241" alt="Capture" src="https://user-images.githubusercontent.com/67531873/124280977-e597a580-db66-11eb-9d4c-86dcba129a06.PNG">

9.When I choose the car.csv and try to use grapesAgri1::descApp() without header it shows me this error -
car.csv already have a header. so if you uncheck header system will consider the first row also as input, which is qualitative and hence the error.

please see this also

Regards!

**Comment by adithirgis** [comment]
> I have already added that, is that ok or any other issue, I didn't understand the comment, sorry

You will have to add reference inside the paper.md as well, for which ever package you are referring to. Please refer to the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) of JOSS. 

> car.csv already have a header. so if you uncheck header system will consider the first row also as input, which is qualitative and hence the error.

Can you please mention in the ReadMe file or any appropriate place that header is necessary in the file or it creates a confusion. I hope I made sense. 

Cheers! 
Adithi

**Comment by pratheesh3780** [comment]
@adithirgis 
All suggestions were made 
1. All apps updated
2.  Download formatting issue in word was due to a bug in KableExtra. Now html option is only there
3. Download image issues rectified
4. Package version added in description
5. code style and made uniform
6. Testing added for all apps
7. Validation added for unintended user inputs
8. reading materials added in Readme
9. Suggestions in paper.md incorporated

😰 

😌 
Cheers!

**Comment by adithirgis** [comment]
Hello! 

Can you please add the points corresponding to the list above, first issue I created. I see that you have almost completed the changes I asked except adding the reference. 
Once you add the corresponding response to the right number. I will proceed with the reviewing. 

Thanks a lot.

**Comment by pratheesh3780** [comment]
@adithirgis paper.bib is not showing in References...no idea why

**Comment by adithirgis** [comment]
Hi! 

1. I think because there are no references inside the paper. Can I please again request you to go through the example in the submission guidelines of JOSS. 

eg - where `[@astropy]` is a reference 
`Astropy package [@astropy]`

And also requesting you to add the numbers and the corresponding response to it as per my first list (since its difficult to keep track), so that I can check them off. 

2. Also for this line - 

`Some of the webapplications like WASP (https://ccari.res.in/waspnew.html) and OPSTAT (http://14.139.232.166/opstat/) used by agricultural research community were userfriendly and very simple to use but these applications don't provide opportunities to generate plots and graphs.`

If this sounds correct change it to - 

`Some of the web applications like WASP (https://ccari.res.in/waspnew.html) and OPSTAT (http://14.139.232.166/opstat/) used by agricultural research community are user friendly but these applications don't provide options to generate plots and graphs.`

3. Please also do mention what package you used to style your code. 

4. And also run `devtools::check()`, some tests seem to fail. 

Thanks! 
Adithi

**Comment by pratheesh3780** [comment]
> Thank you for submitting to JOSS, I enjoyed reviewing this package. Congratulations!
> 
> Starting my review here. To avoid system errors I tried to run this package on [RStudio cloud](https://rstudio.cloud/).
> 
> 1. Can you please add references in [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md) using [paper.bib](https://github.com/adithirgis/grapesAgri1/blob/master/paper.bib).

- **Sorry for not following up. I'm on to it**

> 2. Can you please mention whether `grapesAgri1` has been cited or referenced anywhere and if yes where please add it.

- **Its new but its now used by a lot of students not cited anywhere**

> 3. As mentioned in the [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md) -
>    "Scientist and research students were in trouble to find a suitable platform for their data analysis and also to publish the research output in quality journals. Most of the softwares available for data analysis are proprietary or lacks a simple user interface. Though several online platforms were available for data analysis, they are not much updated up to the current publication standards at international level."

- **I have added these suggestions in [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md)** 

>    Can the authors please mention software name they have come across which are proprietary, lack simple user interface or not updated to current standards and do not provide graphs, thus providing a comparative study.

- **I have added these suggestions in [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md)**

> 4. Also in the [DESCRIPTION](https://github.com/adithirgis/grapesAgri1/blob/master/DESCRIPTION) of the package, please add the version number of the packages which are being imported, this might resolve the conflict of versions.

- **Package version added**

> 5. Styling of the code is not uniform , please refer to this guide for styling or you could also use `styler` package, sometimes `=` is used for assignment and in other places `<-` is used (recommend choosing one style and sticking with it)
>    eg -
>    `result=as.data.frame( anova(anvaTable) ); trtmeans<-out$means`

- **Styling and changes were done, "=" is used uniformly everywhere,  styler package is used**

> 6. Spacing in code is inconsistent. Also the code lines stretch very long, beyond the recommended 80 characters or 120 characters. Here is a resource which could be helpful - https://devguide.ropensci.org/building.html#code-style, http://adv-r.had.co.nz/Style.html and https://www.tidyverse.org/blog/2017/12/styler-1.0.0/.

- **Done**

> 7. Can you please point me to the tests folder of this application? I do not seem to find the test folder in the package. Please add test units for automatically testing your application. Tests for functions will also be required. Examples from JOSS - https://github.com/michaellevy/gwdegree/tree/master/tests/testthat, https://github.com/PsyChiLin/EFAshiny/tree/master/tests/testthat, https://github.com/OttaviaE/DscoreApp/tree/master/tests, https://github.com/pmcharrison/psychTestR/tree/master/tests/testthat.

- **Test where added using shinytest and testthat [here](https://github.com/pratheesh3780/grapesAgri1/tree/master/tests)**

> 8. I got three notes while checking the package using `devtools::check()`. I would suggest adding `.bib` and `.md` extensions to the `.Rbuildignore` file.  And another problem I faced is that I require `kableExtra` as an import not suggests, because I tried installing the package and it still says I need to install the `kableExtra`, `summarytools`, and for `grapesAgri1::ttApp()` it required `PairedData`.

- **Done. All these packages are now in import**

>    `checking package dependencies ... NOTE Packages suggested but not available for checking:   'kableExtra', 'summarytools', 'desplot', 'PairedData'`.

- **Resolved issue**

> 9. When I choose the car.csv and try to use `grapesAgri1::descApp()` without header it shows me this error -
>    ![image](https://user-images.githubusercontent.com/63432077/124088055-35477580-da70-11eb-99cb-a22d146ddac8.png)

- **Header should be ticked if you are using a file with header, I hope it is clear**

> 10. For correlation analysis report download in `grapesAgri1::corrApp()` function for Simple_corelation, for html version the formatting looks fine, while the word/docx version does not seem very intuitive, is there a way to format it correctly, and the pdf version is not downloaded in my windows 10 system. Error for pdf version is - `Warning in system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) : '"pdflatex"' not found Warning: Error in : LaTeX failed to compile report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.`-
> 
> ![image](https://user-images.githubusercontent.com/63432077/124088155-4abc9f80-da70-11eb-94e8-292f65436892.png)
> ![image](https://user-images.githubusercontent.com/63432077/124088184-514b1700-da70-11eb-8cd5-89088086dda6.png)
> ![image](https://user-images.githubusercontent.com/63432077/124088215-57d98e80-da70-11eb-9cdf-f405124fbdc9.png)
> 


**- Problem cause by KableExtra as several apps are incoporated together. Removed PDF and Word download option, now only html, good to go!**


> 1. Also when I don't select any options it shows this error, is it possible to show these errors as warnings or have an option already selected -
> 
> ![image](https://user-images.githubusercontent.com/63432077/124088362-7dff2e80-da70-11eb-95b4-506d596c6f78.png)
> 


**- Validation added for unintended user inputs** 


> 1. For this function `grapesAgri1::crdApp()` for the below selected parameters I am not able to generate the table is there some mistake I am making, please explain the data used here `unequal_replication.csv` and others to understand the functionality better -
>    ![image](https://user-images.githubusercontent.com/63432077/124089613-ab98a780-da71-11eb-9e6b-e741f4be643d.png)

- **Validation added for unintended user inputs** 

> 2. It would be great if these functions - `grapesAgri1::layoutApp()` and `grapesAgri1::rbdApp()` and its application are explained in the [ReadMe](https://github.com/adithirgis/grapesAgri1#readme) file. And to add both the apps work well with the `mango data.csv`.

**- layout app generates field layout of experiments to perform experiment in field.  Additional reading materials added in Readme**

> 3. Paper suggestions - I will [pr](https://github.com/pratheesh3780/grapesAgri1/pull/2), please feel free to ignore some if you feel its not grammatically correct. Changes are in bold and strikeout.

- **All your suggestions were incorporated**

> 4. Extra suggestion, if possible the Community guidelines can be mentioned in the documentation or the [ReadMe](https://github.com/adithirgis/grapesAgri1#readme) file instead of [paper.md](https://github.com/adithirgis/grapesAgri1/blob/master/paper.md)

**- Done**

<img width="448" alt="Capture" src="https://user-images.githubusercontent.com/67531873/125074508-fdc57280-e0da-11eb-8907-8aecb6362941.PNG">

**Comment by pratheesh3780** [comment]
R-cmd check seems ok. Screen shot in previous comment.

**Comment by adithirgis** [comment]
Hello,

Thanks for following up soon! Really appreciate it. 

I have a few things in my checklist now to end the review - 

- [ ] Run `devtools::check()` and `devtools::test()`, some tests seem to fail in my system. Let me add the error I get here. This is using the latest version of the app also `devtools::check()` also gives the same error.  

```r
> devtools::test()
i Loading grapesAgri1
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
i Testing grapesAgri1
√ |  OK F W S | Context
x |   0 1     | app-file [70.3 s]                                                          
-------------------------------------------------------------------------------------------
Failure (testdesc.R:6:3): descApp_testing
Not all shinytest scripts passed for D:/Dropbox/ILKConsultancy/grapesAgri1/inst/desc: mytest

Diff output:
==== mytest ====
diff "C:\\Users\\Dell\\AppData\\Local\\Temp\\Rtmpo35dGe\\shinytest-diff-1eec7d913a59/mytest-expected/001.json" "C:\\Users\\Dell\\AppData\\Local\\Temp\\Rtmpo35dGe\\shinytest-diff-1eec7d913a59/mytest-current/001.json"
1,68c1,68
< {
<   "input": {
<     "dataset": "iris",
<     "file1": null,
<     "header": true,
<     "req": "summary",
<     "shiny_height": 744,
<     "shiny_width": 992
<   },
<   "output": {
<     "bygroup": null,
<     "data_set": {
<       "html": "<div class=\"form-group shiny-input-container\">\n  <label class=\"control-label\" id=\"dataset-label\" for=\"dataset\">Choose a dataset:<\/label>\n  <div>\n    <select id=\"dataset\"><option value=\"iris\" selected>iris<\/option>\n<option value=\"pressure\">pressure<\/option>\n<option value=\"cars\">cars<\/option><\/select>\n    <script type=\"application/json\" data-for=\"dataset\" data-nonempty=\"\">{\"plugins\":[\"selectize-plugin-a11y\"]}<\/script>\n  <\/div>\n<\/div>\n<a id=\"downloadData\" class=\"btn btn-default shiny-download-link butt1\" href=\"\" target=\"_blank\" download>\n  <i class=\"fa fa-download\" role=\"presentation\" aria-label=\"download icon\"><\/i>\n  Download csv file to test\n<\/a>",
<       "deps": [
<         {
<           "name": "selectize",
<           "version": "0.12.4",
<           "src": {
<             "href": "shared/selectize"
<           },
<           "meta": null,
<           "script": [
<             "js/selectize.min.js",
<             "accessibility/js/selectize-plugin-a11y.min.js"
<           ],
<           "stylesheet": "css/selectize.bootstrap3.css",
<           "head": null,
<           "attachment": null,
<           "package": null,
<           "all_files": true
<         },
<         {
<           "name": "font-awesome",
<           "version": "5.13.0",
<           "src": {
<             "href": "font-awesome-5.13.0"
<           },
<           "meta": null,
<           "script": null,
<           "stylesheet": [
<             "css/all.min.css",
<             "css/v4-shims.min.css"
<           ],
<           "head": null,
<           "attachment": null,
<           "all_files": true
<         }
<       ]
<     },
<     "image_down": null,
<     "nort": "",
<     "note": {
<       "html": " <h4> To perform analysis using your own dataset prepare excel file in csv format by reading instruction below  <\/h4>\n<p>\n<ui>\n<li>Open a new blank excel file<\/li>\n<li>Copy and paste observations into a new sheet (use only one sheet) of a new excel file<\/li>\n<li>Observations should be pasted as columns <\/li>\n<li>Don't type or delete anything on other cells without data<\/li>\n<li>You can use any names for your columns. No space is allowed in the Column name. If space is required use underscore ‘_’ or ‘.’ full stop; for example ‘Variable name’ should be written as Variable_name or Variable.name<\/li>\n<li>Data should be arranged towards upper left corner and row above the data should not be left blank <\/li>\n<li>Don't type and delete anything on other cells without data. If so select those cells, right click and click clear contents <\/li>\n<li>Give names to all column, Don't add any unnecessary columns that is not required for analysis<\/li>\n<li>Once all these are done, your file is ready. Now save it as CSV file. <\/li>\n<li><b>Upload file by clicking browse in the app <\/b><\/li>\n<\/ui>\n<\/p>\n<h5> You can download a model data set from below and test the App  <\/h5>\n",
<       "deps": [
< 
<       ]
<     },
<     "plot": null,
<     "summaryout": null,
<     "text3": null,
<     "var": null,
<     "var1": null,
<     "var2": null
<   },
<   "export": {
< 
<   }
< }
---
> {
>   "input": {
>     "dataset": "iris",
>     "file1": null,
>     "header": true,
>     "req": "summary",
>     "shiny_height": 744,
>     "shiny_width": 992
>   },
>   "output": {
>     "bygroup": null,
>     "data_set": {
>       "html": "<div class=\"form-group shiny-input-container\">\n  <label class=\"control-label\" id=\"dataset-label\" for=\"dataset\">Choose a dataset:<\/label>\n  <div>\n    <select id=\"dataset\"><option value=\"iris\" selected>iris<\/option>\n<option value=\"pressure\">pressure<\/option>\n<option value=\"cars\">cars<\/option><\/select>\n    <script type=\"application/json\" data-for=\"dataset\" data-nonempty=\"\">{\"plugins\":[\"selectize-plugin-a11y\"]}<\/script>\n  <\/div>\n<\/div>\n<a id=\"downloadData\" class=\"btn btn-default shiny-download-link butt1\" href=\"\" target=\"_blank\" download>\n  <i class=\"fa fa-download\" role=\"presentation\" aria-label=\"download icon\"><\/i>\n  Download csv file to test\n<\/a>",
>       "deps": [
>         {
>           "name": "selectize",
>           "version": "0.12.4",
>           "src": {
>             "href": "shared/selectize"
>           },
>           "meta": null,
>           "script": [
>             "js/selectize.min.js",
>             "accessibility/js/selectize-plugin-a11y.min.js"
>           ],
>           "stylesheet": "css/selectize.bootstrap3.css",
>           "head": null,
>           "attachment": null,
>           "package": null,
>           "all_files": true
>         },
>         {
>           "name": "font-awesome",
>           "version": "5.13.0",
>           "src": {
>             "href": "font-awesome-5.13.0"
>           },
>           "meta": null,
>           "script": null,
>           "stylesheet": [
>             "css/all.min.css",
>             "css/v4-shims.min.css"
>           ],
>           "head": null,
>           "attachment": null,
>           "all_files": true
>         }
>       ]
>     },
>     "image_down": null,
>     "nort": "",
>     "note": {
>       "html": " <h4> To perform analysis using your own dataset prepare excel file in csv format by reading instruction below  <\/h4>\n<p>\n<ui>\n<li>Open a new blank excel file<\/li>\n<li>Copy and paste observations into a new sheet (use only one sheet) of a new excel file<\/li>\n<li>Observations should be pasted as columns <\/li>\n<li>Don't type or delete anything on other cells without data<\/li>\n<li>You can use any names for your columns. No space is allowed in the Column name. If space is required use underscore ‘_’ or ‘.’ full stop; for example ‘Variable name’ should be written as Variable_name or Variable.name<\/li>\n<li>Data should be arranged towards upper left corner and row above the data should not be left blank <\/li>\n<li>Don't type and delete anything on other cells without data. If so select those cells, right click and click clear contents <\/li>\n<li>Give names to all column, Don't add any unnecessary columns that is not required for analysis<\/li>\n<li>Once all these are done, your file is ready. Now save it as CSV file. <\/li>\n<li><b>Upload file by clicking browse in the app <\/b><\/li>\n<\/ui>\n<\/p>\n<h5> You can download a model data set from below and test the App  <\/h5>\n",
>       "deps": [
> 
>       ]
>     },
>     "plot": null,
>     "summaryout": null,
>     "text3": null,
>     "var": null,
>     "var1": null,
>     "var2": null
>   },
>   "export": {
> 
>   }
> }

If this is expected, use `snapshotUpdate('D:/Dropbox/ILKConsultancy/grapesAgri1/inst/desc')` to update
-------------------------------------------------------------------------------------------
x |   0 1     | app-file [21.4 s]                                                          
-------------------------------------------------------------------------------------------
Failure (testttest.R:6:3): ttest_testing
Not all shinytest scripts passed for D:/Dropbox/ILKConsultancy/grapesAgri1/inst/comp_mean: mytest

Diff output:
==== mytest ====
diff "C:\\Users\\Dell\\AppData\\Local\\Temp\\Rtmpo35dGe\\shinytest-diff-1eec37707b35/mytest-expected/001.json" "C:\\Users\\Dell\\AppData\\Local\\Temp\\Rtmpo35dGe\\shinytest-diff-1eec37707b35/mytest-current/001.json"
1,81c1,81
< {
<   "input": {
<     "dataset": "iris",
<     "file1": null,
<     "header": true,
<     "req1": "ttest"
<   },
<   "output": {
<     "data_set": {
<       "html": "<div class=\"form-group shiny-input-container\">\n  <label class=\"control-label\" id=\"dataset-label\" for=\"dataset\">Choose a dataset:<\/label>\n  <div>\n    <select id=\"dataset\"><option value=\"iris\" selected>iris<\/option>\n<option value=\"rock\">rock<\/option>\n<option value=\"pressure\">pressure<\/option><\/select>\n    <script type=\"application/json\" data-for=\"dataset\" data-nonempty=\"\">{\"plugins\":[\"selectize-plugin-a11y\"]}<\/script>\n  <\/div>\n<\/div>\n<a id=\"downloadData\" class=\"btn btn-default shiny-download-link butt1\" href=\"\" target=\"_blank\" download>\n  <i class=\"fa fa-download\" role=\"presentation\" aria-label=\"download icon\"><\/i>\n  Download csv file to test\n<\/a>",
<       "deps": [
<         {
<           "name": "selectize",
<           "version": "0.12.4",
<           "src": {
<             "href": "shared/selectize"
<           },
<           "meta": null,
<           "script": [
<             "js/selectize.min.js",
<             "accessibility/js/selectize-plugin-a11y.min.js"
<           ],
<           "stylesheet": "css/selectize.bootstrap3.css",
<           "head": null,
<           "attachment": null,
<           "package": null,
<           "all_files": true
<         },
<         {
<           "name": "font-awesome",
<           "version": "5.13.0",
<           "src": {
<             "href": "font-awesome-5.13.0"
<           },
<           "meta": null,
<           "script": null,
<           "stylesheet": [
<             "css/all.min.css",
<             "css/v4-shims.min.css"
<           ],
<           "head": null,
<           "attachment": null,
<           "all_files": true
<         }
<       ]
<     },
<     "ftest": null,
<     "image_down": null,
<     "note1": null,
<     "note2": null,
<     "note3": null,
<     "note4": null,
<     "note5": null,
<     "ottest": null,
<     "plot": null,
<     "pttest": null,
<     "slider": null,
<     "start_note": {
<       "html": " <h4> To perform analysis using your own dataset, prepare excel file in csv format by reading instruction below  <\/h4>\n<p>\n<ui>\n<li>Open a new blank excel file<\/li>\n<li>Copy and paste observations into a new sheet (use only one sheet) of a new excel file<\/li>\n<li>Groups to be compared should be pasted as columns <\/li>\n<li>Don't type or delete anything on other cells without data<\/li>\n<li>You can use any names for your columns. No space is allowed in the Column name. If space is required use underscore ‘_’ or ‘.’ full stop; for example ‘Variable name’ should be written as Variable_name or Variable.name<\/li>\n<li>Data should be arranged towards upper left corner and row above the data should not be left blank <\/li>\n<li>Type 'NA' in the cell with no observation<\/li>\n<li>Don't type and delete anything on other cells without data. If so select those cells, right click and click clear contents <\/li>\n<li>Give names to all column, Don't add any unnecessary columns that is not required for analysis<\/li>\n<li>Once all these are done, your file is ready. Now save it as CSV file. <\/li>\n<li><b>Upload file by clicking browse in the app <\/b><\/li>\n<\/ui>\n<\/p>\n<p>\n<b> Things to remember while doing t-test<\/b>\n<li>Note that, unpaired two-samples t-test can be used only under certain conditions: <\/li>\n<li>First condition: each of the two groups of samples being compared, should be normally distributed. This can be checked using Shapiro-Wilk test and other data visualization techniques [use grapes::descApp()]<\/li>\n<li>Second condition: Variances of the two groups should be equal.\nThis can be checked using Homogenity of variance test (F test) available\nwith in the app. <\/li>\n<li>If the variances of the two groups being compared are different (heteroscedasticity), it’s possible to use the Welch t test, an adaptation of Student t-test. <\/li>\n<li>Welch t test and F-test are available within the app<\/li>\n<\/p>\n<b> You can download a model data set from below and test the App  <\/b>\n",
<       "deps": [
< 
<       ]
<     },
<     "summary1": null,
<     "summary2": null,
<     "summary3": null,
<     "summary4": null,
<     "summary5": null,
<     "ttest": null,
<     "var": null,
<     "var1": null,
<     "var2": null,
<     "var3": null,
<     "var4": null,
<     "var5": null,
<     "wttest": null
<   },
<   "export": {
< 
<   }
< }
---
> {
>   "input": {
>     "dataset": "iris",
>     "file1": null,
>     "header": true,
>     "req1": "ttest"
>   },
>   "output": {
>     "data_set": {
>       "html": "<div class=\"form-group shiny-input-container\">\n  <label class=\"control-label\" id=\"dataset-label\" for=\"dataset\">Choose a dataset:<\/label>\n  <div>\n    <select id=\"dataset\"><option value=\"iris\" selected>iris<\/option>\n<option value=\"rock\">rock<\/option>\n<option value=\"pressure\">pressure<\/option><\/select>\n    <script type=\"application/json\" data-for=\"dataset\" data-nonempty=\"\">{\"plugins\":[\"selectize-plugin-a11y\"]}<\/script>\n  <\/div>\n<\/div>\n<a id=\"downloadData\" class=\"btn btn-default shiny-download-link butt1\" href=\"\" target=\"_blank\" download>\n  <i class=\"fa fa-download\" role=\"presentation\" aria-label=\"download icon\"><\/i>\n  Download csv file to test\n<\/a>",
>       "deps": [
>         {
>           "name": "selectize",
>           "version": "0.12.4",
>           "src": {
>             "href": "shared/selectize"
>           },
>           "meta": null,
>           "script": [
>             "js/selectize.min.js",
>             "accessibility/js/selectize-plugin-a11y.min.js"
>           ],
>           "stylesheet": "css/selectize.bootstrap3.css",
>           "head": null,
>           "attachment": null,
>           "package": null,
>           "all_files": true
>         },
>         {
>           "name": "font-awesome",
>           "version": "5.13.0",
>           "src": {
>             "href": "font-awesome-5.13.0"
>           },
>           "meta": null,
>           "script": null,
>           "stylesheet": [
>             "css/all.min.css",
>             "css/v4-shims.min.css"
>           ],
>           "head": null,
>           "attachment": null,
>           "all_files": true
>         }
>       ]
>     },
>     "ftest": null,
>     "image_down": null,
>     "note1": null,
>     "note2": null,
>     "note3": null,
>     "note4": null,
>     "note5": null,
>     "ottest": null,
>     "plot": null,
>     "pttest": null,
>     "slider": null,
>     "start_note": {
>       "html": " <h4> To perform analysis using your own dataset, prepare excel file in csv format by reading instruction below  <\/h4>\n<p>\n<ui>\n<li>Open a new blank excel file<\/li>\n<li>Copy and paste observations into a new sheet (use only one sheet) of a new excel file<\/li>\n<li>Groups to be compared should be pasted as columns <\/li>\n<li>Don't type or delete anything on other cells without data<\/li>\n<li>You can use any names for your columns. No space is allowed in the Column name. If space is required use underscore ‘_’ or ‘.’ full stop; for example ‘Variable name’ should be written as Variable_name or Variable.name<\/li>\n<li>Data should be arranged towards upper left corner and row above the data should not be left blank <\/li>\n<li>Type 'NA' in the cell with no observation<\/li>\n<li>Don't type and delete anything on other cells without data. If so select those cells, right click and click clear contents <\/li>\n<li>Give names to all column, Don't add any unnecessary columns that is not required for analysis<\/li>\n<li>Once all these are done, your file is ready. Now save it as CSV file. <\/li>\n<li><b>Upload file by clicking browse in the app <\/b><\/li>\n<\/ui>\n<\/p>\n<p>\n<b> Things to remember while doing t-test<\/b>\n<li>Note that, unpaired two-samples t-test can be used only under certain conditions: <\/li>\n<li>First condition: each of the two groups of samples being compared, should be normally distributed. This can be checked using Shapiro-Wilk test and other data visualization techniques [use grapes::descApp()]<\/li>\n<li>Second condition: Variances of the two groups should be equal.\nThis can be checked using Homogenity of variance test (F test) available\nwith in the app. <\/li>\n<li>If the variances of the two groups being compared are different (heteroscedasticity), it’s possible to use the Welch t test, an adaptation of Student t-test. <\/li>\n<li>Welch t test and F-test are available within the app<\/li>\n<\/p>\n<b> You can download a model data set from below and test the App  <\/b>\n",
>       "deps": [
> 
>       ]
>     },
>     "summary1": null,
>     "summary2": null,
>     "summary3": null,
>     "summary4": null,
>     "summary5": null,
>     "ttest": null,
>     "var": null,
>     "var1": null,
>     "var2": null,
>     "var3": null,
>     "var4": null,
>     "var5": null,
>     "wttest": null
>   },
>   "export": {
> 
>   }
> }

If this is expected, use `snapshotUpdate('D:/Dropbox/ILKConsultancy/grapesAgri1/inst/comp_mean')` to update
-------------------------------------------------------------------------------------------

== Results ================================================================================
Duration: 91.8 s

[ FAIL 2 | WARN 0 | SKIP 0 | PASS 0 ]
```

- [x]  Also for this line -

`Some of the webapplications like WASP (https://ccari.res.in/waspnew.html) and OPSTAT (http://14.139.232.166/opstat/) used by agricultural research community were userfriendly and very simple to use but these applications don't provide opportunities to generate plots and graphs.`

If this sounds correct change it to -

`Some of the web applications like WASP (https://ccari.res.in/waspnew.html) and OPSTAT (http://14.139.232.166/opstat/) used by agricultural research community are user friendly but these applications don't provide options to generate plots and graphs.`



- Also not sure if we need this section here https://github.com/adithirgis/grapesAgri1/blob/master/joss/paper.md#package-dependencies-and-details-of-functions-used I will leave it to the editor. 

- This is for my reference - which package did you use for styling your code? 

- Also I will leave it to you the code at some places does spill over 120 characters eg- 

`out = agricolae::duncan.test(d[, input$yield], d[, input$treatment], result[3, 1], result[3, 3], alpha = 0.05, group = TRUE, main = NULL, console = FALSE)`

- And the usage of `<-` is always preferred over `=` as mentioned previously. This is optional and feel free to ignore it. 


Thanks!
Adithi

**Comment by pratheesh3780** [comment]
> Hello,
> 
> Thanks for following up soon! Really appreciate it.
> 
> I have a few things in my checklist now to end the review -
> 
> * [ ]  Run `devtools::check()` and `devtools::test()`, some tests seem to fail in my system. Let me add the error I get here. This is using the latest version of the app also `devtools::check()` also gives the same error.
> 
**

- changed and tested again rectified the issue
- devtools::check()
- 
<img width="394" alt="R CMD check" src="https://user-images.githubusercontent.com/67531873/125106156-f4e59880-e0fc-11eb-9d07-569b6d1aadc8.PNG">

- devtools::test()
- 
<img width="409" alt="devtoolstest" src="https://user-images.githubusercontent.com/67531873/125106225-075fd200-e0fd-11eb-8a1f-ac73be1f1634.PNG">

<img width="414" alt="devtoolscheck1" src="https://user-images.githubusercontent.com/67531873/125106256-121a6700-e0fd-11eb-8a2f-09e1af5bea0e.PNG">


**
> * [ ]   Also for this line -
> 
> `Some of the webapplications like WASP (https://ccari.res.in/waspnew.html) and OPSTAT (http://14.139.232.166/opstat/) used by agricultural research community were userfriendly and very simple to use but these applications don't provide opportunities to generate plots and graphs.`
> 
> If this sounds correct change it to -
> 
> `Some of the web applications like WASP (https://ccari.res.in/waspnew.html) and OPSTAT (http://14.139.232.166/opstat/) used by agricultural research community are user friendly but these applications don't provide options to generate plots and graphs.`



- **It is changed already please check**


> 
> * Also not sure if we need this section here https://github.com/adithirgis/grapesAgri1/blob/master/joss/paper.md#package-dependencies-and-details-of-functions-used I will leave it to the editor.

**- ok**

> * This is for my reference - which package did you use for styling your code?

**- styler**

Thank you.

**Comment by adithirgis** [comment]
Hello, 

Thanks! 

Could you please check this again? This is from the latest pull. Let me know if this is my system issue. 

```r
devtools::test()
i Loading grapesAgri1
i Testing grapesAgri1
√ |  OK F W S | Context
x |   0 1     | app-file [9.9 s]                                                           
-------------------------------------------------------------------------------------------
Error (testdesc.R:6:3): descApp_testing
Error: Cannot find shiny port number. Error:
Loading required package: shiny

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Loading required package: grid

Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows


Attaching package: 'pastecs'

The following object is masked from 'package:magrittr':

    extract

The following objects are masked from 'package:dplyr':

    first, last

Loading required package: ggplot2
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. base::lapply(...)
  4. shinytest:::FUN(X[[i]], ...)
  5. base::source(testname, local = env)
  7. [ base::eval(...) ] with 1 more call
  9. ShinyDriver$new("../../")
 10. shinytest:::initialize(...)
 11. shinytest:::sd_initialize(...)
 12. private$startShiny(...)
 13. shinytest:::sd_startShiny(...)
-------------------------------------------------------------------------------------------
x |   0 1     | app-file [27.7 s]                                                          
-------------------------------------------------------------------------------------------
Failure (testttest.R:6:3): ttest_testing
Not all shinytest scripts passed for D:/Dropbox/ILKConsultancy/grapesAgri1/inst/comp_mean: mytest

Diff output:
==== mytest ====
diff "C:\\Users\\Dell\\AppData\\Local\\Temp\\RtmpiSn5IW\\shinytest-diff-a3c7be07fc/mytest-expected/001.json" "C:\\Users\\Dell\\AppData\\Local\\Temp\\RtmpiSn5IW\\shinytest-diff-a3c7be07fc/mytest-current/001.json"
1,81c1,81
< {
<   "input": {
<     "dataset": "iris",
<     "file1": null,
<     "header": true,
<     "req1": "ttest"
<   },
<   "output": {
<     "data_set": {
<       "html": "<div class=\"form-group shiny-input-container\">\n  <label class=\"control-label\" id=\"dataset-label\" for=\"dataset\">Choose a dataset:<\/label>\n  <div>\n    <select id=\"dataset\"><option value=\"iris\" selected>iris<\/option>\n<option value=\"rock\">rock<\/option>\n<option value=\"pressure\">pressure<\/option><\/select>\n    <script type=\"application/json\" data-for=\"dataset\" data-nonempty=\"\">{\"plugins\":[\"selectize-plugin-a11y\"]}<\/script>\n  <\/div>\n<\/div>\n<a id=\"downloadData\" class=\"btn btn-default shiny-download-link butt1\" href=\"\" target=\"_blank\" download>\n  <i class=\"fa fa-download\" role=\"presentation\" aria-label=\"download icon\"><\/i>\n  Download csv file to test\n<\/a>",
<       "deps": [
<         {
<           "name": "selectize",
<           "version": "0.12.4",
<           "src": {
<             "href": "shared/selectize"
<           },
<           "meta": null,
<           "script": [
<             "js/selectize.min.js",
<             "accessibility/js/selectize-plugin-a11y.min.js"
<           ],
<           "stylesheet": "css/selectize.bootstrap3.css",
<           "head": null,
<           "attachment": null,
<           "package": null,
<           "all_files": true
<         },
<         {
<           "name": "font-awesome",
<           "version": "5.13.0",
<           "src": {
<             "href": "font-awesome-5.13.0"
<           },
<           "meta": null,
<           "script": null,
<           "stylesheet": [
<             "css/all.min.css",
<             "css/v4-shims.min.css"
<           ],
<           "head": null,
<           "attachment": null,
<           "all_files": true
<         }
<       ]
<     },
<     "ftest": null,
<     "image_down": null,
<     "note1": null,
<     "note2": null,
<     "note3": null,
<     "note4": null,
<     "note5": null,
<     "ottest": null,
<     "plot": null,
<     "pttest": null,
<     "slider": null,
<     "start_note": {
<       "html": " <h4> To perform analysis using your own dataset, prepare excel file in csv format by reading instruction below  <\/h4>\n<p>\n<ui>\n<li>Open a new blank excel file<\/li>\n<li>Copy and paste observations into a new sheet (use only one sheet) of a new excel file<\/li>\n<li>Groups to be compared should be pasted as columns <\/li>\n<li>Don't type or delete anything on other cells without data<\/li>\n<li>You can use any names for your columns. No space is allowed in the Column name. If space is required use underscore ‘_’ or ‘.’ full stop; for example ‘Variable name’ should be written as Variable_name or Variable.name<\/li>\n<li>Data should be arranged towards upper left corner and row above the data should not be left blank <\/li>\n<li>Type 'NA' in the cell with no observation<\/li>\n<li>Don't type and delete anything on other cells without data. If so select those cells, right click and click clear contents <\/li>\n<li>Give names to all column, Don't add any unnecessary columns that is not required for analysis<\/li>\n<li>Once all these are done, your file is ready. Now save it as CSV file. <\/li>\n<li><b>Upload file by clicking browse in the app <\/b><\/li>\n<\/ui>\n<\/p>\n<p>\n<b> Things to remember while doing t-test<\/b>\n<li>Note that, unpaired two-samples t-test can be used only under certain conditions: <\/li>\n<li>First condition: each of the two groups of samples being compared, should be normally distributed. This can be checked using Shapiro-Wilk test and other data visualization techniques [use grapes::descApp()]<\/li>\n<li>Second condition: Variances of the two groups should be equal.\nThis can be checked using Homogenity of variance test (F test) available\nwith in the app. <\/li>\n<li>If the variances of the two groups being compared are different (heteroscedasticity), it’s possible to use the Welch t test, an adaptation of Student t-test. <\/li>\n<li>Welch t test and F-test are available within the app<\/li>\n<\/p>\n<b> You can download a model data set from below and test the App  <\/b>\n",
<       "deps": [
< 
<       ]
<     },
<     "summary1": null,
<     "summary2": null,
<     "summary3": null,
<     "summary4": null,
<     "summary5": null,
<     "ttest": null,
<     "var": null,
<     "var1": null,
<     "var2": null,
<     "var3": null,
<     "var4": null,
<     "var5": null,
<     "wttest": null
<   },
<   "export": {
< 
<   }
< }
---
> {
>   "input": {
>     "dataset": "iris",
>     "file1": null,
>     "header": true,
>     "req1": "ttest"
>   },
>   "output": {
>     "data_set": {
>       "html": "<div class=\"form-group shiny-input-container\">\n  <label class=\"control-label\" id=\"dataset-label\" for=\"dataset\">Choose a dataset:<\/label>\n  <div>\n    <select id=\"dataset\"><option value=\"iris\" selected>iris<\/option>\n<option value=\"rock\">rock<\/option>\n<option value=\"pressure\">pressure<\/option><\/select>\n    <script type=\"application/json\" data-for=\"dataset\" data-nonempty=\"\">{\"plugins\":[\"selectize-plugin-a11y\"]}<\/script>\n  <\/div>\n<\/div>\n<a id=\"downloadData\" class=\"btn btn-default shiny-download-link butt1\" href=\"\" target=\"_blank\" download>\n  <i class=\"fa fa-download\" role=\"presentation\" aria-label=\"download icon\"><\/i>\n  Download csv file to test\n<\/a>",
>       "deps": [
>         {
>           "name": "selectize",
>           "version": "0.12.4",
>           "src": {
>             "href": "shared/selectize"
>           },
>           "meta": null,
>           "script": [
>             "js/selectize.min.js",
>             "accessibility/js/selectize-plugin-a11y.min.js"
>           ],
>           "stylesheet": "css/selectize.bootstrap3.css",
>           "head": null,
>           "attachment": null,
>           "package": null,
>           "all_files": true
>         },
>         {
>           "name": "font-awesome",
>           "version": "5.13.0",
>           "src": {
>             "href": "font-awesome-5.13.0"
>           },
>           "meta": null,
>           "script": null,
>           "stylesheet": [
>             "css/all.min.css",
>             "css/v4-shims.min.css"
>           ],
>           "head": null,
>           "attachment": null,
>           "all_files": true
>         }
>       ]
>     },
>     "ftest": null,
>     "image_down": null,
>     "note1": null,
>     "note2": null,
>     "note3": null,
>     "note4": null,
>     "note5": null,
>     "ottest": null,
>     "plot": null,
>     "pttest": null,
>     "slider": null,
>     "start_note": {
>       "html": " <h4> To perform analysis using your own dataset, prepare excel file in csv format by reading instruction below  <\/h4>\n<p>\n<ui>\n<li>Open a new blank excel file<\/li>\n<li>Copy and paste observations into a new sheet (use only one sheet) of a new excel file<\/li>\n<li>Groups to be compared should be pasted as columns <\/li>\n<li>Don't type or delete anything on other cells without data<\/li>\n<li>You can use any names for your columns. No space is allowed in the Column name. If space is required use underscore ‘_’ or ‘.’ full stop; for example ‘Variable name’ should be written as Variable_name or Variable.name<\/li>\n<li>Data should be arranged towards upper left corner and row above the data should not be left blank <\/li>\n<li>Type 'NA' in the cell with no observation<\/li>\n<li>Don't type and delete anything on other cells without data. If so select those cells, right click and click clear contents <\/li>\n<li>Give names to all column, Don't add any unnecessary columns that is not required for analysis<\/li>\n<li>Once all these are done, your file is ready. Now save it as CSV file. <\/li>\n<li><b>Upload file by clicking browse in the app <\/b><\/li>\n<\/ui>\n<\/p>\n<p>\n<b> Things to remember while doing t-test<\/b>\n<li>Note that, unpaired two-samples t-test can be used only under certain conditions: <\/li>\n<li>First condition: each of the two groups of samples being compared, should be normally distributed. This can be checked using Shapiro-Wilk test and other data visualization techniques [use grapes::descApp()]<\/li>\n<li>Second condition: Variances of the two groups should be equal.\nThis can be checked using Homogenity of variance test (F test) available\nwith in the app. <\/li>\n<li>If the variances of the two groups being compared are different (heteroscedasticity), it’s possible to use the Welch t test, an adaptation of Student t-test. <\/li>\n<li>Welch t test and F-test are available within the app<\/li>\n<\/p>\n<b> You can download a model data set from below and test the App  <\/b>\n",
>       "deps": [
> 
>       ]
>     },
>     "summary1": null,
>     "summary2": null,
>     "summary3": null,
>     "summary4": null,
>     "summary5": null,
>     "ttest": null,
>     "var": null,
>     "var1": null,
>     "var2": null,
>     "var3": null,
>     "var4": null,
>     "var5": null,
>     "wttest": null
>   },
>   "export": {
> 
>   }
> }

If this is expected, use `snapshotUpdate('D:/Dropbox/ILKConsultancy/grapesAgri1/inst/comp_mean')` to update
-------------------------------------------------------------------------------------------

== Results ================================================================================
Duration: 37.7 s

[ FAIL 2 | WARN 0 | SKIP 0 | PASS 0 ]
```
I completed most of the review. Will wait for this one. 

Thank you!
Adithi

**Comment by pratheesh3780** [comment]
Ok I got it; hopefully a 'loadTimeout ' in ShinyDriver$new will resolve the issue. Will get back to you shortly.

Thank you for all the support!

**Comment by pratheesh3780** [comment]
Hi!
Done all what is possible....hope for the best
these are my results

==> devtools::check()

i Updating grapesAgri1 documentation
i Loading grapesAgri1
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
Writing NAMESPACE
Writing NAMESPACE
-- Building ---------------------------- grapesAgri1 --
Setting env vars:
* CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
* CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
* CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
-------------------------------------------------------
v  checking for file 'D:\PERMANENT ASSETS\R package\grapesAgri1/DESCRIPTION' ...
-  preparing 'grapesAgri1': (407ms)
v  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
   Loading required namespace: grapesAgri1
-  saving partial Rd database (525ms)
-  checking for LF line-endings in source and make files and shell scripts (519ms)
-  checking for empty or unneeded directories
-  building 'grapesAgri1_1.0.0.tar.gz'
   
-- Checking ---------------------------- grapesAgri1 --
Setting env vars:
* _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
* _R_CHECK_CRAN_INCOMING_       : FALSE
* _R_CHECK_FORCE_SUGGESTS_      : FALSE
* NOT_CRAN                      : true
-- R CMD check -----------------------------------------------------------------
-  using log directory 'D:/PERMANENT ASSETS/R package/grapesAgri1.Rcheck'
-  using R version 4.0.4 (2021-02-15)
-  using platform: x86_64-w64-mingw32 (64-bit)
-  using session charset: ISO8859-1
-  using options '--no-manual --as-cran'
v  checking for file 'grapesAgri1/DESCRIPTION'
-  checking extension type ... Package
-  this is package 'grapesAgri1' version '1.0.0'
-  package encoding: UTF-8
v  checking package namespace information
v  checking package dependencies (5.4s)
v  checking if this is a source package ... 
v  checking if there is a namespace
v  checking for executable files (689ms)
v  checking for hidden files and directories ... 
v  checking for portable file names ... 
v  checking serialization versions ...
v  checking whether package 'grapesAgri1' can be installed (3.3s)
v  checking installed package size ... 
v  checking package directory (695ms)
v  checking for future file timestamps (32.4s)
v  checking DESCRIPTION meta-information (352ms)
v  checking top-level files
v  checking for left-over files ...
v  checking index information
v  checking package subdirectories ... 
v  checking R files for non-ASCII characters ... 
v  checking R files for syntax errors ... 
v  checking whether the package can be loaded ... 
v  checking whether the package can be loaded with stated dependencies ... 
v  checking whether the package can be unloaded cleanly ... 
v  checking whether the namespace can be loaded with stated dependencies ... 
v  checking whether the namespace can be unloaded cleanly (441ms)
v  checking loading without being on the library search path (765ms)
v  checking dependencies in R code (561ms)
v  checking S3 generic/method consistency (550ms)
v  checking replacement functions (344ms)
v  checking foreign function calls (337ms)
v  checking R code for possible problems (2.5s)
v  checking Rd files (893ms)
v  checking Rd metadata ... 
v  checking Rd line widths ... 
v  checking Rd cross-references ... 
v  checking for missing documentation entries (340ms)
v  checking for code/documentation mismatches (796ms)
v  checking Rd \usage sections (782ms)
v  checking Rd contents ... 
v  checking for unstated dependencies in examples ... 
v  checking examples (660ms)
v  checking for unstated dependencies in 'tests' ... 
-  checking tests ...
v  Running 'testthat.R' [20s] (19.9s)
v  checking for non-standard things in the check directory (19.9s)
v  checking for detritus in the temp directory
   
   
-- R CMD check results ---------------------------------- grapesAgri1 1.0.0 ----
Duration: 1m 15.8s

0 errors v | 0 warnings v | 0 notes v

R CMD check succeeded

--------------------------------------------------------------------------------------------------


==> devtools::test()

i Loading grapesAgri1
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
i Testing grapesAgri1
v |  OK F W S | Context
v |   1   11   | app-file [11.7 s]                     
-------------------------------------------------------
Warning (testdesc.R:2:1): (code run outside of `test_that()`)
package 'shinytest' was built under R version 4.0.5
Backtrace:
 1. base::library(shinytest) testdesc.R:2:0
 2. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'shiny' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny::loadSupport(appDir, renv = sharedEnv, globalrenv = NULL)
 17. base::require(shiny)
 22. base::library(...)
 23. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'shinyWidgets' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(shinyWidgets)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'rmarkdown' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(rmarkdown)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'knitr' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(knitr)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'dplyr' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(dplyr)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'gridGraphics' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(gridGraphics)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'kableExtra' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(kableExtra)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'pastecs' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(pastecs)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'ggplot2' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(ggpubr)
 21. base::.getRequiredPackages2(pkgInfo, quietly = quietly)
 22. base::library(...)
 23. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testdesc.R:6:3): descApp_testing
package 'summarytools' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testdesc.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(summarytools)
 21. base:::testRversion(pkgInfo, package, pkgpath)
-------------------------------------------------------
v |   1   3   | app-file [6.1 s]                       
-------------------------------------------------------
Warning (testttest.R:6:3): ttest_testing
package 'PairedData' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testttest.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(PairedData)
 21. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testttest.R:6:3): ttest_testing
package 'gld' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testttest.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(PairedData)
 21. base::.getRequiredPackages2(pkgInfo, quietly = quietly)
 22. base::library(...)
 23. base:::testRversion(pkgInfo, package, pkgpath)

Warning (testttest.R:6:3): ttest_testing
package 'reshape2' was built under R version 4.0.5
Backtrace:
  1. shinytest::expect_pass(testApp(appDir, compareImages = FALSE)) testttest.R:6:2
  2. shinytest::testApp(appDir, compareImages = FALSE)
  3. shinytest:::app_path(appDir, "appDir")
  4. shinytest:::is_app(path)
 12. shiny::shinyAppDir(path)
 13. shiny:::shinyAppDir_appR("app.R", appDir, options = options)
 14. shiny:::appObj()
 15. shiny:::func(fname, ...)
 16. shiny:::sourceUTF8(fullpath, envir = new.env(parent = sharedEnv))
 17. [ base::eval(...) ] with 1 more call
 20. base::library(reshape2)
 21. base:::testRversion(pkgInfo, package, pkgpath)
-------------------------------------------------------

== Results ============================================
Duration: 17.9 s

[ FAIL 0 | WARN 14 | SKIP 0 | PASS 2 ]

Nice code.

**Comment by adithirgis** [comment]
Hello, 

I still get the error, I think its screen shot issue which can arises if the size of the screens differ (this is an issue with shinytest package). I will wrap up the review now. Congratulations!

And three optional comments - 

- styling of the code can be restricted to 120 characters
- usage of `<-` instead of `=` is preferred 
- and reducing the number of packages imported, getting the package into CRAN will be difficult, suggestion would be to use base R packages. 

Thanks!
Adithi

**Comment by adithirgis** [comment]
Hi, 

I just realised you could also check why the `R-CMD check` is failing, this can probably point out to why I am still getting test failed. 

Thanks!

**Comment by pratheesh3780** [comment]
Hi,
I also noticed that, I was working on that ....R-CMD check is passing for mac and ubuntu but not for windows. Trying to resolve.
let me also add ....really appreciate your efforts in supporting open-source initiatives. Lucky to have you as the reviewer. Learnt a lot! 
Thank you!

**Comment by pratheesh3780** [comment]
Hi,
finally resolved the issue, R-CMD check is passing. It might be related to how git on Windows converts \n to \r\n. so resolved it by adding      
'- name: Windows git setup
        if: runner.os == 'Windows'
        run:
          git config --global core.autocrlf false'
in yaml

phew!! 😌

I think issue is I should keep my git config core.autocrlf false, so you can clone in to a windows system without any issues.

Thank You

**Comment by pratheesh3780** [comment]
Hi
You can also try set autocrlf to false before pull
git config --global core.autocrlf false
and please let me know if this works,then I can add rest of the tests.
Thank you!

**Comment by adithirgis** [comment]
Hi, 

I checked again but I still get the errors, but I am pretty sure its because the sizes of the image issue. I think its not resolvable as of now using shinytest. Check this - https://github.com/rstudio/shinytest/issues/300 and https://github.com/rstudio/shinytest/issues/315.

Thanks

**Comment by adithirgis** [comment]
I will close this issue now. All the best.

Adithi
